/*
 * This source file was generated by the Gradle 'init' task
 */
package org.scriptorium;

import org.junit.jupiter.api.Test;
import org.scriptorium.application.Main;

import static org.junit.jupiter.api.Assertions.*;

class MainTest {
}
